version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lu_estilo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # Expõe a porta 5432 internamente no contêiner
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lu_estilo
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      TEST_DB_URL: postgresql://test_user:test_password@test_db:5432/test_db  # Atualizado para usar 'test_db'

volumes:
  pgdata:
  pgdata_test:
